language: ruby
bundler_args: ''
rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - jruby-19mode
  - rbx-2.1
  - rbx-2.2
matrix:
  allow_failures:
    - rvm: rbx-2.2
notifications:
  flowdock: 9feba89b66463a4fa85f2ede04c6dc82
